name: Android CI

on: workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle
      
    - name: Decode Keystore
      run: |
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 -d > worldcentre.jks
          # chmod 644 worldcentre.jks
          echo "worldcentre.jks" >> $GITHUB_PATH
    
    - name: Build Release APK
      env:
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}   
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew clean aR
      
      # 打包完成之后进行上传
    - uses: actions/upload-artifact@v4
      with:
          path: chat/build/outputs/apk/*/chat-release.apk
